### ISSUE TITLE
Fix error importing package

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/codemirror-lang-wren#4]
If I try to import the package using:

```typescript
const { wren } = await import('@exercism/codemirror-lang-wren')
```

I get the following error:

```
TS2307: Cannot find module '@exercism/codemirror-lang-wren' or its corresponding type declarations.
```

Changing the dynamic import to a regular one results in the same error:

```typescript
import { wren } from '@exercism/codemirror-lang-wren'
```

Importing a file using `import '@exercism/codemirror-lang-wren/dist/index.es'` _does_ work.

The `node_modules/@exercism/codemirror-lang-wren` directory has the following files:

```
dist/index.cjs
dist/index.es.js
LICENSE
package.json
README.md
```

**Comment by ErikSchierboom** [comment]
CC @SleeplessByte

**Comment by SleeplessByte** [comment]
Will fix!
